apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: ui-{{ .Chart.Name }}-{{ .Release.Name }}-serv
            port:
              number: {{ .Values.ports.ui.source }}
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
